### PR TITLE
Fix EventInit not giving users roles on client ready

### LINKED ISSUE #29: EventInit bug - won't give roles
EventInit runs on the bot "ready" event, basically when the bot has successfully initialized. 
It doesn't automatically give everyone the new role that was created for the recurring scheduled event. It makes the new custom role and then acts like it doesn't see the people already marked interested in the scheduled event.

### PR DESCRIPTION
**Pull request by leavism**
Closes #29 
- EventInit now gives users the custom role associated with scheduled events
- Custom role names now mention the recurring rate instead of the start date and time if it is a recurring scheduled event

### CODE REVIEW

File: src/lib/LovelaceClient.ts [hunk 1]
```diff
@@ -47,3 +47,8 @@ declare module '@sapphire/pieces' {
 		scheduledEventsService: ScheduleEventsService;
 	}
 }
+declare module 'discord.js' {
+    interface GuildScheduledEvent {
+        customRoleId?: string; // Make it optional if it might not always be present
```
Comment (oderanwosu) [inline src/lib/LovelaceClient.ts:52]: Not the biggest fan of modifying third-party interfaces. I'd make a seperate object that takes in a guild scheduled event and a custom role id rather than augmenting it.

File: src/lib/ScheduledEventService.ts [hunk 2]
```diff
@@ -18,56 +18,58 @@ import { reasonableTruncate } from './utils';
...
-				return false;
+				return null;
 			}
 			const dbEntry = await database.findScheduledEvent(scheduledEvent.id);
 			if (dbEntry) {
 				client.logger.info(
 					`Scheduled event ${yellow(scheduledEvent.name)} already exists in the database. Skipping processing in scheduled events service.`,
 				);
-				return true;
+				scheduledEvent.customRoleId = dbEntry.roleId;
```
Comment (oderanwosu) [inline src/lib/ScheduledEventService.ts:41]: awkward logic due to augmentation.

**Review by oderanwosu — CHANGES_REQUESTED** [review]

File: src/lib/ScheduledEventService.ts (hunk 2 above)
Comment (oderanwosu) [reply src/lib/ScheduledEventService.ts:41]: oops meant to include the return statement as well

**Review by oderanwosu — APPROVED** [review]
lgtm
